hold:
  target:
    entity:
      integration: gungors
  fields:
    state:
      required: true
      example: '{"position": 0}'
      selector:
        object:
    duration:
      selector:
        duration:
    until:
      selector:
        datetime:
    mode:
      default: strict
      selector:
        select:
          options:
            - strict
            - manual

release:
  target:
    entity:
      integration: gungors

set_pid_gain:
  target:
    entity:
      integration: gungors
      domain: climate
  fields:
    kp:
      selector:
        number: {mode: box, min: 0, max: 100000, step: any}
    ki:
      selector:
        number: {mode: box, min: 0, max: 100000, step: any}
    kd:
      selector:
        number: {mode: box, min: 0, max: 100000, step: any}
    ke:
      selector:
        number: {mode: box, min: 0, max: 100000, step: any}

set_pid_mode:
  target:
    entity:
      integration: gungors
      domain: climate
  fields:
    mode:
      required: true
      selector:
        select:
          options:
            - auto
            - "off"

clear_integral:
  target:
    entity:
      integration: gungors
      domain: climate
  fields:
    value:
      default: 0
      selector:
        number: {mode: box, min: -100, max: 100, step: any}

reload:
